@startuml childActor
[*] --> retryState
retryState : enter/ loadDeviceInfo()

retryState -down-> failedState : Throwable
retryState -down-> okState : DeviceInfo

okState : enter/ set receive timeout,
okState: enter/ storeInfo(di)
okState : exit/ storeInfo()
okState : MessageCallArgs/ call rpc
okState  -down-> failedState : RuntimeException
okState -> [*] : ReceiveTimeout


failedState: enter/ set retry timer
failedState: exit/ cancel retry timer
failedState -> retryState : reconnect
failedState: MessageCallArgs/ send error or stash



@enduml